name = "flux-docs01"
compatibility_date = "2025-06-04"
account_id = "fbb4ae392a349c3a4c7b713ec57dbc29"
main = "dist/_worker.js"
workers_dev = true

[build]
command = "pnpm run build"
upload.format = "service-worker"
upload.dir = "./dist"
